/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as DoctorContractJson } from "../Doctor.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";

// Custom types for the contract
export namespace DoctorTypes {
  export type Fields = {
    owner: Address;
    insuranceBalance: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    getBalance: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    receivePayment: {
      params: CallContractParams<{ amount: bigint }>;
      result: CallContractResult<null>;
    };
    withdraw: {
      params: CallContractParams<{ amount: bigint }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    getBalance: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    receivePayment: {
      params: SignExecuteContractMethodParams<{ amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    withdraw: {
      params: SignExecuteContractMethodParams<{ amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<DoctorInstance, DoctorTypes.Fields> {
  encodeFields(fields: DoctorTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      []
    );
  }

  at(address: string): DoctorInstance {
    return new DoctorInstance(address);
  }

  tests = {
    getBalance: async (
      params: Omit<
        TestContractParamsWithoutMaps<DoctorTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getBalance", params, getContractByCodeHash);
    },
    receivePayment: async (
      params: TestContractParamsWithoutMaps<
        DoctorTypes.Fields,
        { amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "receivePayment", params, getContractByCodeHash);
    },
    withdraw: async (
      params: TestContractParamsWithoutMaps<
        DoctorTypes.Fields,
        { amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "withdraw", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: DoctorTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const Doctor = new Factory(
  Contract.fromJson(
    DoctorContractJson,
    "",
    "e74a8fc8dca69a39e38ac7392c4e421c06934451ea529ff57ad97e0c20b06239",
    []
  )
);
registerContract(Doctor);

// Use this class to interact with the blockchain
export class DoctorInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<DoctorTypes.State> {
    return fetchContractState(Doctor, this);
  }

  view = {
    getBalance: async (
      params?: DoctorTypes.CallMethodParams<"getBalance">
    ): Promise<DoctorTypes.CallMethodResult<"getBalance">> => {
      return callMethod(
        Doctor,
        this,
        "getBalance",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    receivePayment: async (
      params: DoctorTypes.CallMethodParams<"receivePayment">
    ): Promise<DoctorTypes.CallMethodResult<"receivePayment">> => {
      return callMethod(
        Doctor,
        this,
        "receivePayment",
        params,
        getContractByCodeHash
      );
    },
    withdraw: async (
      params: DoctorTypes.CallMethodParams<"withdraw">
    ): Promise<DoctorTypes.CallMethodResult<"withdraw">> => {
      return callMethod(
        Doctor,
        this,
        "withdraw",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    getBalance: async (
      params: DoctorTypes.SignExecuteMethodParams<"getBalance">
    ): Promise<DoctorTypes.SignExecuteMethodResult<"getBalance">> => {
      return signExecuteMethod(Doctor, this, "getBalance", params);
    },
    receivePayment: async (
      params: DoctorTypes.SignExecuteMethodParams<"receivePayment">
    ): Promise<DoctorTypes.SignExecuteMethodResult<"receivePayment">> => {
      return signExecuteMethod(Doctor, this, "receivePayment", params);
    },
    withdraw: async (
      params: DoctorTypes.SignExecuteMethodParams<"withdraw">
    ): Promise<DoctorTypes.SignExecuteMethodResult<"withdraw">> => {
      return signExecuteMethod(Doctor, this, "withdraw", params);
    },
  };

  async multicall<Calls extends DoctorTypes.MultiCallParams>(
    calls: Calls
  ): Promise<DoctorTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends DoctorTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<DoctorTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends DoctorTypes.MultiCallParams | DoctorTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(Doctor, this, callss, getContractByCodeHash);
  }
}
